windowrule = tile class:.*
windowrule = opacity 1 class:.*
windowrule = float class:^(popup)$ # Example using class
windowrule = float title:^(context_menu)$ # Example using title
windowrule = suppress_event maximize class:.* # You'll probably like this.
windowrule = match:class ^google-chrome-beta$, fullscreen_state 1 1
# windowrule = float class ^org.kde.plasma.emojier$ # Example using class

#windowrule = size 99% 90%, class:negative:(kitty)
#windowrule = move onscreen 0.5% 8%, class:negative:(kitty)

#windowrule = size 90% 90%, class:^(kitty)$
#windowrule = move onscreen 5% 8%, class:^(kitty)$
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
